# Generated by Django 5.2.4 on 2025-07-31 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                (
                    "project_type",
                    models.CharField(
                        choices=[("REGULAR", "Regular"), ("FIXCOST", "FixCost")],
                        max_length=20,
                    ),
                ),
                ("present_day", models.FloatField(default=0)),
                ("billable_days", models.FloatField(default=0)),
                ("billable_hours", models.FloatField(blank=True, default=0)),
                ("non_billable_days", models.FloatField(default=0)),
                ("non_billable_hours", models.FloatField(blank=True, default=0)),
                (
                    "resource_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resources.resourcemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Model",
                "verbose_name_plural": "Project Models",
                "db_table": "project_model",
                "ordering": ["project_name"],
            },
        ),
    ]
