# Generated by Django 5.2.4 on 2025-08-01 05:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('resources', '0002_alter_resourcemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='present_day',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='resource_name',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='billable_days',
            field=models.FloatField(default=0, help_text='Total billable days for the project', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='billable_hours',
            field=models.FloatField(default=0, editable=False, help_text='Auto-calculated (billable_days × 8)'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='non_billable_days',
            field=models.FloatField(default=0, help_text='Total non-billable days for the project', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='non_billable_hours',
            field=models.FloatField(default=0, editable=False, help_text='Auto-calculated (non_billable_days × 8)'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Project'), ('FIXED_COST', 'Fixed Cost Project')], default='REGULAR', max_length=20),
        ),
        migrations.AlterModelTable(
            name='projectmodel',
            table=None,
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_day', models.FloatField(default=0, help_text='Days the resource was present for this project', validators=[django.core.validators.MinValueValidator(0)])),
                ('billable_days', models.FloatField(default=0, help_text='Number of billable days', validators=[django.core.validators.MinValueValidator(0)])),
                ('billable_hours', models.FloatField(default=0, editable=False, help_text='Auto-calculated (billable_days × 8)')),
                ('non_billable_days', models.FloatField(default=0, help_text='Number of non-billable days', validators=[django.core.validators.MinValueValidator(0)])),
                ('non_billable_hours', models.FloatField(default=0, editable=False, help_text='Auto-calculated (non_billable_days × 8)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_resources', to='projects.projectmodel')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_allocations', to='resources.resourcemodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='resources',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectResource', through_fields=('project', 'resource'), to='resources.resourcemodel'),
        ),
        migrations.AddConstraint(
            model_name='projectresource',
            constraint=models.UniqueConstraint(fields=('project', 'resource'), name='unique_project_resource'),
        ),
    ]
