# Generated by Django 5.2.4 on 2025-08-01 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('REGULAR', 'Regular Project'), ('FIXED_COST', 'Fixed Cost Project')], default='REGULAR', max_length=20)),
                ('year', models.PositiveIntegerField(help_text='Enter the year for this project report (e.g., 2025)')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Enter the month for this project report (1–12)')),
                ('present_day', models.FloatField(default=0, help_text='Number of days the project was active', validators=[django.core.validators.MinValueValidator(0)])),
                ('billable_days', models.FloatField(default=0, help_text='Number of billable days', validators=[django.core.validators.MinValueValidator(0)])),
                ('non_billable_days', models.FloatField(default=0, help_text='Number of non-billable days', validators=[django.core.validators.MinValueValidator(0)])),
                ('billable_hours', models.FloatField(default=0, editable=False, help_text='Auto-calculated from billable_days × 8')),
                ('non_billable_hours', models.FloatField(default=0, editable=False, help_text='Auto-calculated from non_billable_days × 8')),
                ('is_active', models.BooleanField(default=True, help_text='For soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-year', '-month', 'project_name'],
            },
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='resources',
        ),
        # migrations.RemoveField(
        #     model_name='projectresource',
        #     name='project',
        # ),
        # migrations.RemoveField(
        #     model_name='projectresource',
        #     name='resource',
        # ),
    ]
