# Generated by Django 5.2.4 on 2025-08-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_remove_projectmodel_resources_and_more'),
        ('resources', '0004_resource_delete_resourcemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resources',
            field=models.ManyToManyField(help_text='Multiple resources can be assigned to this project', related_name='assigned_projects', to='resources.resource'),
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
        migrations.DeleteModel(
            name='ProjectResource',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('project_name', 'year', 'month')},
        ),
    ]
