# Generated by Django 5.2.4 on 2025-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_name", models.CharField(max_length=100)),
                ("working_days", models.FloatField(default=0)),
                ("present_day", models.FloatField(default=0)),
                ("present_hours", models.FloatField(blank=True, default=0)),
            ],
            options={
                "verbose_name": "Resource Model",
                "verbose_name_plural": "Resource Models",
                "db_table": "resource_model",
                "ordering": ["resource_name"],
            },
        ),
    ]
