# Generated by Django 5.2.4 on 2025-08-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcemodel',
            options={'ordering': ['resource_name'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='present_day',
            field=models.FloatField(default=0, help_text='Days resource was present'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='present_hours',
            field=models.FloatField(default=0, help_text='Auto-calculated as present_day × 8 hours if not set'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='resource_name',
            field=models.CharField(help_text='Enter the full name of the resource', max_length=100),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='working_days',
            field=models.FloatField(blank=True, help_text='Leave blank to auto-calculate (Mon–Fri + 1st Saturday)', null=True),
        ),
    ]
