# Generated by Django 5.2.4 on 2025-08-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resourcemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemodel',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=8),
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
