# Generated by Django 5.2.4 on 2025-08-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_remove_projectmodel_resources_and_more'),
        ('resources', '0003_resourcemodel_month_resourcemodel_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(help_text='Enter the full name of the resource', max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Enter the year manually (e.g., 2025)')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Enter the month manually (1–12)')),
                ('working_days', models.FloatField(blank=True, help_text='Leave blank to auto-calculate (Mon–Fri + 1st Saturday)', null=True)),
                ('present_day', models.FloatField(default=0, help_text='Days resource was present')),
                ('present_hours', models.FloatField(default=0, help_text='Auto-calculated as present_day × 8 hours if not set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'resources',
                'ordering': ['-year', '-month', 'resource_name'],
                'unique_together': {('resource_name', 'year', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='ResourceModel',
        ),
    ]
